name: Main Workflow Test

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    steps:
      - name: Run main workflow tests
        uses: ./.github/actions/test-main-workflow
        with:
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
